name: Gradle CI

on: 
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build:
    name: 'Build'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - name: 'Git Checkout'
      uses: actions/checkout@v1
    - name: 'Set Up JDK 11'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Run Gradle Build'
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
